[package]
name = "osu-collector-dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.171", features = ["std", "serde_derive"] }
serde_derive = "1.0.171"
serde_json = "1.0.102"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
